openapi: 3.0.0

info:
  title: Learn express and swagger
  description: Learn all about express and api documentation using swagger.
  version: 1.0.1
  contact:
    email: testemail@email.com
    url: "http://localhost:4000"

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: For localhost
    variables: 
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http